# generate-markdown.yml
name: Generate Markdown

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Find DECK.md files
        id: find-deck-files
        run: |
          find . -name "DECK.md" -print > deck-files.txt

      - name: Generate Markdown
        run: |
          while IFS= read -r file; do
            title=$(basename "$file" .md)
            data=$(yq e '.' "$file".yaml)

            # ... rest of your script ...

            # Update the DECK.md file
            echo "## $title ![status](https://img.shields.io/badge/status-$status-$color)
<details $(if [ \"$status\" = \"ONGOING\" ]; then echo \"open\"; fi)>
  <summary>Details</summary>
  <!-- your content here -->
</details>" > "$file"
          done < deck-files.txt
