# generate-markdown.yml
name: Generate Markdown

on:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install yq
        run: |
          sudo apt-get install yq

      - name: Generate Markdown
        run: |
          yq e '.[]' deck-statuses.yaml | while read -r line; do
            title=$(echo "$line" | yq e '.title')
            status=$(echo "$line" | yq e '.status')

            case $status in
              NOT STARTED|NOT--STARTED)
                color="lightgrey"
                ;;
              ONGOING)
                color="yellow"
                ;;
              DONE)
                color="brightgreen"
                ;;
              *)
                color="gray"
                ;;
            esac

            echo "## $title ![status](https://img.shields.io/badge/status-$status-$color)
<details $(if [ \"$status\" = \"ONGOING\" ]; then echo \"open\"; fi)>
  <summary>Details</summary>
  <!-- your content here -->
</details>" >> README.md
          done
